#!/usr/bin/env bash
rm -rf public
cd ../antora-genealogy
git pull
cd -
cd ../antora-immanuel
git pull
cd -
npx antora antora-playbook.yml 
cp  fonts/* public/_/font/
sudo /usr/bin/rm -rf /var/www/krueckeberg.org/docs/*
sudo /usr/bin/cp -r public /var/www/krueckeberg.org/docs
sudo /usr/bin/chown -R root:www-data /var/www/krueckeberg.org/docs
sudo /usr/bin/chmod -R g+w /var/www/krueckeberg.org/docs
