#!/usr/bin/env bash
set -e

echo "=== Antora Build Started: $(date) ==="

#
# 1. CLEAN PREVIOUS BUILD
#
echo "Cleaning previous build..."
rm -rf /home/kurt/play/public-3compo

#
# 2. UPDATE CONTENT REPOS
#
cd /home/kurt/antora-genealogy && git pull
cd /home/kurt/antora-immanuel && git pull
cd /home/kurt/antora-nla && git pull

#
# 3. RUN ANTORA BUILD (3-component playbook)
#
cd /home/kurt/play
npx antora antora-3compo-playbook.yml

#
# 4. COPY FONTS
#
mkdir -p /home/kurt/play/public-3compo/_/font
#cp -u /home/kurt/play/fonts/* \
#      /home/kurt/play/public-3compo/_/font/

#
# 5. DEPLOY TO VPS
#
#
rsync -rzv --progress --delete \
  /home/kurt/play/public-3compo/ \
  kurt@hostwinds:/var/www/krueckeberg.org/docs/public/

echo "=== Antora Build Completed: $(date) ==="
